---

# ***`Encoding Categorical Variables (OneHotEncoder)`***

---

- For Nominal Categorical Data
- In onhoencoder `1` column is always less than total created columns (dummy variable trap)

#### **Import Libraries**

In [13]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import (
    OneHotEncoder,
    LabelEncoder,
    OrdinalEncoder,
)

#### **Load the Dataset**

In [14]:
df = pd.read_csv(r"https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day27-one-hot-encoding/cars.csv")

df.sample(10)

           brand  km_driven    fuel         owner  selling_price
7045      Maruti      40000  Petrol  Second Owner         590000
5907      Maruti      60000  Diesel   First Owner         470000
685         Ford      60000  Petrol   First Owner         370000
7184  Volkswagen      80000  Diesel  Second Owner         280000
4246      Maruti      69779  Petrol   First Owner         600000
5469     Hyundai     120000  Diesel   First Owner         509999
5270    Mahindra      35000  Diesel   First Owner         500000
428        Honda      40000  Diesel   First Owner         700000
1955      Maruti      40000  Petrol   First Owner         225000
719      Hyundai     135000  Diesel   First Owner         335000

In [15]:
df['brand'].nunique()

32

In [16]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [17]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

#### **`OneHotEncoding Using Pandas`**

- Only for Data Analysis.
- For Machine Learning We use `OneHotEncoder`.

In [18]:
pd.get_dummies(df,columns=['fuel','owner']) # 12 new columns will be created

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

- If we use `drop_first=True` then first `OneHotEncoded` column will be dropped automatically.

In [19]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True) # 1 new columns will be created

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

#### **`OneHotEncoding Using Scikit-Learn`**

In [20]:
# split the data into train and test set

# This function is used to split the dataset into training and testing subsets.

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    df.iloc[:, 0:4],   # Features: select the first four columns of the DataFrame 'df'
    df.iloc[:, -1],    # Target variable: select the last column of 'df'
    test_size=0.2,     # Specify that 20% of the data should be used for testing
)

In [ ]:
# Importing the OneHotEncoder from a library (usually scikit-learn)
# This encoder is used to convert categorical variables into a format that can be provided to ML algorithms.

# Create an instance of OneHotEncoder
ohe = OneHotEncoder(drop='first') # drop first category of encoded columns

# Fit the OneHotEncoder on the training data and transform the 'fuel' and 'owner' columns
# This will convert these categorical variables into one-hot encoded format for the training set
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']]).toarray()

# Transform the test data using the previously fitted OneHotEncoder
# This applies the same one-hot encoding to the test set without fitting again
X_test_new = ohe.transform(X_test[['fuel', 'owner']]).toarray()

In [26]:
X_train_new.shape

(6502, 9)

- Now we need to sepratly connect the previous ***2 cloumns*** with ***onehotencoded*** columns

In [22]:
np.hstack((X_train[["brand","km_driven"]].values,X_train_new))

array([['Mahindra', 88754, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 30000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Mahindra', 120000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Mahindra', 70000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Datsun', 5000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Toyota', 80000, 0.0, ..., 1.0, 0.0, 0.0]], dtype=object)

### ***OneHotEncoding with Top Categories***

In [27]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [28]:
counts = df['brand'].value_counts()

In [29]:
df['brand'].nunique()
threshold = 100

In [30]:
# Identify the indices of elements in the 'counts' Series
# that have values less than or equal to a specified 'threshold'.
# These indices will be stored in the variable 'replacement'.
replacement = counts[counts <= threshold].index

In [31]:
# Replace occurrences of brands in the 'replacement' list with the label 'uncommon' 
# in the 'brand' column of the DataFrame 'df'.
# Then, create dummy variables for the 'brand' column, converting it into a one-hot encoded format.

pd.get_dummies(df['brand'].replace(replacement, 'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False

---